-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.UserMutations exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias SignupRequiredArguments =
    { input : Api.InputObject.SignupInput }


signup :
    SignupRequiredArguments
    -> SelectionSet String Api.Object.UserMutations
signup requiredArgs____ =
    Object.selectionForField "String" "signup" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeSignupInput ] Decode.string


type alias LoginRequiredArguments =
    { input : Api.InputObject.LoginInput }


login :
    LoginRequiredArguments
    -> SelectionSet String Api.Object.UserMutations
login requiredArgs____ =
    Object.selectionForField "String" "login" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeLoginInput ] Decode.string


type alias AdminLoginRequiredArguments =
    { input : Api.InputObject.AdminLoginInput }


adminLogin :
    AdminLoginRequiredArguments
    -> SelectionSet String Api.Object.UserMutations
adminLogin requiredArgs____ =
    Object.selectionForField "String" "adminLogin" [ Argument.required "input" requiredArgs____.input Api.InputObject.encodeAdminLoginInput ] Decode.string
